version: '3.2'

services:
  php_study:
    build: ./web
    volumes:
      - ./web:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
  mysql:
    image: mysql:oracle
    volumes:
      - ./mysql:/var/www/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
